// Configuración de Tailwind CSS
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "inverse-on-surface": "#9c9d9d",
                "inverse-primary": "#fdd400",
                "outline-variant": "#acadad",
                "on-surface": "#2d2f2f",
                "tertiary": "#00675f",
                "on-error-container": "#520c00",
                "error": "#b02500",
                "secondary-container": "#ffc3bd",
                "on-secondary-fixed-variant": "#a60010",
                "surface-dim": "#d3d5d5",
                "surface-tint": "#6d5a00",
                "primary-container": "#fdd400",
                "surface-bright": "#f6f6f6",
                "on-primary": "#fff2ce",
                "surface-container": "#e7e8e8",
                "secondary-fixed-dim": "#ffb0a7",
                "on-surface-variant": "#5a5c5c",
                "on-tertiary-container": "#005a53",
                "on-primary-fixed-variant": "#645300",
                "primary": "#6d5a00",
                "surface-container-lowest": "#ffffff",
                "on-secondary": "#ffefed",
                "surface-variant": "#dbdddd",
                "outline": "#767777",
                "secondary-dim": "#a40010",
                "tertiary-dim": "#005a53",
                "secondary": "#b7131a",
                "on-tertiary-fixed-variant": "#00655d",
                "on-primary-container": "#594a00",
                "primary-fixed": "#fdd400",
                "inverse-surface": "#0c0f0f",
                "tertiary-fixed-dim": "#72e4d7",
                "on-primary-fixed": "#433700",
                "on-error": "#ffefec",
                "secondary-fixed": "#ffc3bd",
                "error-container": "#f95630",
                "error-dim": "#b92902",
                "tertiary-fixed": "#81f3e5",
                "primary-dim": "#5f4e00",
                "on-background": "#2d2f2f",
                "tertiary-container": "#81f3e5",
                "on-tertiary": "#bffff5",
                "surface-container-low": "#f0f1f1",
                "surface": "#f6f6f6",
                "primary-fixed-dim": "#edc600",
                "background": "#f6f6f6",
                "on-secondary-container": "#94000d",
                "on-tertiary-fixed": "#004640",
                "on-secondary-fixed": "#700007",
                "surface-container-high": "#e1e3e3",
                "surface-container-highest": "#dbdddd"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Be Vietnam Pro"],
                "label": ["Plus Jakarta Sans"]
            }
        },
    },
}